import { Exception } from "../utils/typing/Exception";

export const USER_EXCEPTIONS = {
    AlreadyExists: {
        statusCode: 400,
        message: "User already exists"
    },

    ServiceUnavailable: {
        statusCode: 503,
        message: "Users service unavalable"
    },

    NotFound: {
        statusCode: 404,
        message: "User not found"
    },

    NotAuthorized: {
        statusCode: 401,
        message:
            "Authorization token niether is not valid or is not generated by server"
    }
} as const satisfies Record<string, Exception>;
